# Generated by Django 6.0.3 on 2026-04-30 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_sheet', models.URLField(blank=True, max_length=500, null=True)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed')], default='pending', max_length=20)),
                ('first_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed')], default='pending', max_length=20)),
                ('review_assigned', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reviews', to='accounts.mentor')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reviews', to='accounts.reviewer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='accounts.student')),
            ],
            options={
                'ordering': ['-review_assigned'],
            },
        ),
    ]
