# Generated by Django 6.0.3 on 2026-06-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='students', to='accounts.document'),
        ),
    ]
