# Generated by Django 6.0.3 on 2026-06-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
