# Generated by Django 6.0.3 on 2026-04-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_reviewassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewassignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='reviewassignment',
            old_name='review_assigned',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='reviewassignment',
            name='first_status',
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
