# Generated by Django 6.0.3 on 2026-06-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='expertise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
