# Generated by Django 6.0.3 on 2026-04-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_mentor_user_alter_reviewer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
