# Generated by Django 6.0.3 on 2026-06-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_role_alter_accounts_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='course',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='number_of_installments',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
