# Generated by Django 6.0.3 on 2026-04-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_reviewassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_review_related',
            field=models.BooleanField(default=False),
        ),
    ]
