# Generated by Django 6.0.3 on 2026-05-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_feepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='agreement_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='escalation_flag',
            field=models.BooleanField(default=False),
        ),
    ]
