# Generated by Django 6.0.3 on 2026-04-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_chatmessage_is_review_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_review_related',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='action',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
