# Generated by Django 6.0.3 on 2026-05-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_agreement_signed_student_escalation_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
