# Generated by Django 6.0.3 on 2026-06-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_mentor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='week_back_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
