# Generated by Django 6.0.3 on 2026-05-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_feepayment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentweekreview',
            name='week_back_from',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentweekreview',
            name='week_back_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentweekreview',
            name='week_back_status',
            field=models.CharField(choices=[('no', 'No'), ('repeated', 'Yes - Repeated'), ('completed', 'Yes - Completed')], default='no', max_length=20),
        ),
    ]
