# Generated by Django 6.0.3 on 2026-05-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_chatmessage_is_review_related_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='action',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
