# Generated by Django 6.0.3 on 2026-06-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_task_options_remove_task_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('pending approval', 'Pending Approval'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='assigned', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='reviewassignment',
            unique_together={('mentor', 'reviewer', 'student', 'week')},
        ),
    ]
