# Generated by Django 6.0.3 on 2026-05-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_chatmessage_is_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('pending approval', 'Pending Approval'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
