# Generated by Django 6.0.3 on 2026-05-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_reviewassignment_status_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
