# Generated by Django 6.0.3 on 2026-05-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_accounts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_mentor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_reviewer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('mentor', 'Mentor'), ('reviewer', 'Reviewer'), ('accounts', 'Accounts')], default='student', max_length=20),
        ),
    ]
