# Generated by Django 6.0.3 on 2026-04-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='content',
            field=models.TextField(),
        ),
    ]
