# Generated by Django 6.0.3 on 2026-05-18 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_is_accounts_remove_user_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
    ]
