# Generated by Django 6.0.3 on 2026-04-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_module_is_public_alter_module_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='content',
            field=models.TextField(help_text='HTML or Markdown content for the module'),
        ),
    ]
