# Generated by Django 6.0.3 on 2026-05-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_module_work_document_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='work_document_url',
        ),
        migrations.AddField(
            model_name='reviewfolder',
            name='column1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reviewfolder',
            name='completed_notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='reviewfolder',
            name='expert_i',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reviewfolder',
            name='key_me',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reviewfolder',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewfolder',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reviewfolder',
            name='student_roster',
            field=models.TextField(blank=True, help_text='Comma separated student names'),
        ),
    ]
