# Generated by Django 6.0.3 on 2026-05-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_module_work_document_url_reviewfolder_column1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewfolder',
            name='column1',
        ),
        migrations.RemoveField(
            model_name='reviewfolder',
            name='completed_notes',
        ),
        migrations.RemoveField(
            model_name='reviewfolder',
            name='expert_i',
        ),
        migrations.RemoveField(
            model_name='reviewfolder',
            name='key_me',
        ),
    ]
