# Generated by Django 6.0.3 on 2026-05-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_reviewfolder_column1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewfolder',
            name='student_roster',
        ),
    ]
