# Generated by Django 6.0.3 on 2026-04-04 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_public',
        ),
        migrations.AddField(
            model_name='module',
            name='is_common',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='StudentModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_modules', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'module')},
            },
        ),
    ]
