# Generated by Django 6.0.3 on 2026-05-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_reviewfolder_student_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentweekreview',
            name='extra_workouts_mark',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Extra workouts mark out of 5', null=True),
        ),
        migrations.AddField(
            model_name='studentweekreview',
            name='progress_video',
            field=models.URLField(blank=True, help_text='Progress video link', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentweekreview',
            name='progress_video_mark',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Progress video mark out of 5', null=True),
        ),
        migrations.AddField(
            model_name='studentweekreview',
            name='review_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Review score out of 20', null=True),
        ),
        migrations.AlterField(
            model_name='studentweekreview',
            name='english_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Score out of 5', null=True),
        ),
        migrations.AlterField(
            model_name='studentweekreview',
            name='total_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Total score out of 35', null=True),
        ),
    ]
