# Generated by Django 6.0.3 on 2026-05-05 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_studentweekreview_extra_workouts_mark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('github', 'GitHub Repository'), ('typing', 'Typing Club Progress'), ('tech_seminar', 'Tech Seminar Video'), ('progress_video', 'Weekly Progress Video')], max_length=20)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('marks', models.PositiveSmallIntegerField(blank=True, help_text='0-5', null=True)),
                ('mentor_feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.student')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.module')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'week', 'submission_type')},
            },
        ),
    ]
