# Generated by Django 6.0.3 on 2026-04-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
