# Generated by Django 6.0.3 on 2026-05-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='break_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Total break time in minutes'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_reason',
            field=models.TextField(blank=True, help_text='Reason for checking out (if early or unusual)'),
        ),
    ]
