# Generated by Django 6.0.3 on 2026-05-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_attendancerecord_break_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentweekreview',
            name='github_repo',
            field=models.URLField(blank=True, help_text='GitHub repository link for this week', max_length=500, null=True),
        ),
    ]
