# Generated by Django 6.0.3 on 2026-04-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_batch_student_student_batch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
