# Generated by Django 6.0.3 on 2026-05-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_studentweekreview_github_repo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentweekreview',
            name='github_repo',
        ),
    ]
