# Generated by Django 6.0.3 on 2026-04-07 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_delete_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors', to='accounts.batch'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewers', to='accounts.batch'),
        ),
    ]
