# Generated by Django 6.0.3 on 2026-05-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_studentweekreview_github_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('pending approval', 'Pending Approval'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending approval', max_length=20),
        ),
    ]
