# Generated by Django 6.0.3 on 2026-05-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_reviewassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='week',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='work_documents',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
