# Generated by Django 6.0.3 on 2026-04-14 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_student_aadhaar_address_student_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='aadhaar_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='student',
            name='govt_id_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='govt_id_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_relation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='taluk',
        ),
        migrations.RemoveField(
            model_name='student',
            name='village',
        ),
        migrations.RemoveField(
            model_name='student',
            name='work_experience',
        ),
    ]
