# Generated by Django 6.0.3 on 2026-04-16 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_student_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_dashboard_access',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
