# Generated by Django 6.0.3 on 2026-04-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_user_last_dashboard_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='unlock_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
