# Generated by Django 6.0.3 on 2026-04-16 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_module_is_locked_module_unlock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_modules', to='accounts.module'),
        ),
    ]
