# Generated by Django 6.0.3 on 2026-04-16 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_module_prerequisite'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWeekReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(blank=True, max_length=100)),
                ('advisor_name', models.CharField(blank=True, max_length=100)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('task_status', models.CharField(blank=True, choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Needs Improvement', 'Needs Improvement')], max_length=50)),
                ('feedback', models.TextField(blank=True)),
                ('extra_workouts', models.TextField(blank=True, help_text='YouTube video links or descriptions')),
                ('english_review', models.TextField(blank=True)),
                ('star_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('total_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reviews', to='accounts.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_reviews', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'module')},
            },
        ),
    ]
