# Generated by Django 6.0.3 on 2026-04-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_studentweekreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentweekreview',
            name='admin_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentweekreview',
            name='mentor_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentweekreview',
            name='reviewer_remarks',
            field=models.TextField(blank=True),
        ),
    ]
