# Generated by Django 6.0.3 on 2026-04-18 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_studentweekreview_admin_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(auto_now_add=True)),
                ('update_text', models.TextField(blank=True)),
                ('extra_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('week_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='accounts.studentweekreview')),
            ],
        ),
    ]
