# Generated by Django 6.0.3 on 2026-04-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_weekupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
