# Generated by Django 6.0.3 on 2026-04-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_reviewer_experience_reviewer_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentweekreview',
            name='english_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Score out of 20', null=True),
        ),
        migrations.AlterField(
            model_name='studentweekreview',
            name='extra_workouts',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Need Improvement', 'Need Improvement'), ('Not Completed', 'Not Completed')], help_text='Status of extra workouts', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentweekreview',
            name='task_status',
            field=models.CharField(blank=True, choices=[('Task Completed', 'Task Completed'), ('Task Need Improvement', 'Task Need Improvement'), ('Task Critical', 'Task Critical'), ('Task Not Completed', 'Task Not Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentweekreview',
            name='total_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Total score out of 20', null=True),
        ),
    ]
