# Generated by Django 6.0.3 on 2026-04-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_chatmessage_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentweekreview',
            name='admin_remarks',
        ),
        migrations.RemoveField(
            model_name='studentweekreview',
            name='mentor_remarks',
        ),
        migrations.RemoveField(
            model_name='studentweekreview',
            name='reviewer_remarks',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentweekreview',
            name='extra_workouts',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Need Improvement', 'Need Improvement'), ('Not Completed', 'Not Completed')], max_length=30),
        ),
    ]
