# Generated by Django 6.0.3 on 2026-04-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_reviewfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewfolder',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviewfolder',
            name='week',
            field=models.CharField(max_length=100),
        ),
    ]
