# Generated by Django 6.0.3 on 2026-04-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_reviewfolder_meeting_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewfolder',
            options={'ordering': ['-review_date', 'week_folder', 'student__user__username']},
        ),
        migrations.AddField(
            model_name='reviewfolder',
            name='week_folder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reviewfolder',
            name='week',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
