# Generated by Django 6.0.3 on 2026-04-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_reviewfolder_options_reviewfolder_week_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewfolder',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
