# Generated by Django 6.0.3 on 2026-04-24 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('student', 'mentor')},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.reviewer'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('student_mentor', 'Student ↔ Mentor'), ('student_reviewer', 'Student ↔ Reviewer'), ('mentor_reviewer', 'Mentor ↔ Reviewer')], default='student_mentor', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.mentor'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('mentor', 'reviewer'), ('student', 'mentor'), ('student', 'reviewer')},
        ),
    ]
