# Generated by Django 6.0.3 on 2026-04-24 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_chatroom_unique_together_chatroom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.reviewer'),
        ),
    ]
