# Generated by Django 6.0.3 on 2026-04-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_student_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewfolder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reviewfolder',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='reviewfolder',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='When this review period ends', null=True),
        ),
        migrations.AddField(
            model_name='reviewfolder',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='When this review period starts', null=True),
        ),
    ]
