# Generated by Django 6.0.3 on 2026-04-25 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_remove_reviewfolder_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewfolder',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='reviewfolder',
            name='start_time',
        ),
        migrations.AddField(
            model_name='reviewfolder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_review_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewfolder',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_review_folders', to=settings.AUTH_USER_MODEL),
        ),
    ]
