# Generated by Django 6.0.3 on 2026-04-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_reviewer_course_alter_reviewer_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='available_days',
            field=models.JSONField(blank=True, default=list, help_text='List of weekdays (0=Monday, 6=Sunday)'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='available_from',
            field=models.TimeField(blank=True, help_text='Start time (e.g. 09:00)', null=True),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='available_to',
            field=models.TimeField(blank=True, help_text='End time (e.g. 17:00)', null=True),
        ),
    ]
