# Generated by Django 6.0.3 on 2026-04-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_mentordocument_studentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
