# Generated by Django 6.0.3 on 2026-04-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_mentor_full_name_reviewer_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.IntegerField(blank=True, help_text='week_number', null=True),
        ),
    ]
